// cuda_backend.h — optional NVIDIA GPU offload for linear projections.
//
// Zero build-time dependency: the CUDA *driver* API is dlopen()ed at runtime
// (libcuda.so.1) and the matvec kernels ship as PTX embedded in the binary
// (src/cuda_ptx.inc, regenerated by `make ptx` from kernels/cuda_kernels.cu).
// On a machine without an NVIDIA driver every entry point degrades cleanly:
// available() returns false and nothing is ever placed on the GPU.
//
// Nothing here is touched unless a caller asks for GPU layers (--gpu-layers N),
// so the default CPU path stays byte-identical.
//
// Supported weight types: Q4_K, Q5_K, Q6_K, F16, F32 with n_in % 256 == 0.
// Activations and outputs are fp32; accumulation is fp32 (no activation
// quantization), so results match the CPU fp32-dequant path (matmul_quant) up
// to summation order.
#pragma once

#include "llm/dtype.h"

#include <cstddef>
#include <cstdint>
#include <string>

namespace llm {
struct WeightRef;

namespace cuda {

// Lazily dlopen libcuda, create a context on device 0 and JIT the embedded PTX.
// Thread-safe; the result is cached. Set SIPLLM_NO_CUDA=1 to force false.
bool available();

// Human-readable reason available() is false ("" when available).
const std::string& unavailable_reason();

// e.g. "NVIDIA GeForce RTX 3050 Ti Laptop GPU (sm_86)".
std::string device_name();

// Free / total device memory in bytes. False if unavailable.
bool mem_info(size_t* free_bytes, size_t* total_bytes);

// True if a weight of type t with inner dimension n_in can run on the GPU.
bool supports(DType t, int64_t n_in);

// Device bytes a [n_out, n_in] weight of type t occupies (Q6_K is re-packed
// from 210- to 212-byte blocks for aligned loads).
size_t weight_bytes(DType t, int64_t n_out, int64_t n_in);

// Upload a host weight in GGUF layout; returns a device pointer (0 on failure:
// unsupported type or out of memory). The host buffer may be freed afterwards.
uint64_t upload_weight(const void* host, DType t, int64_t n_out, int64_t n_in);

// Release a device allocation returned by upload_weight.
void free_weight(uint64_t dev);

// Y[m][n_out] = X[m][n_in] . W^T with W a device weight (W.dev != 0).
// m == 1 is the decode matvec. Throws llm::Error on a CUDA failure.
void linear(float* Y, const WeightRef& W, const float* X, int64_t m);

// Parse a --gpu-layers value: "max"/"all"/"auto"/negative -> -1 (as many as
// fit), otherwise a non-negative layer count.
inline int parse_gpu_layers(const std::string& v) {
    if (v == "max" || v == "all" || v == "auto") return -1;
    const int n = std::stoi(v);
    return n < 0 ? -1 : n;
}

} // namespace cuda
} // namespace llm
